services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on: []
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - API_URL=http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      - api
 # Optional reverse proxy (then expose only 80)
 # nginx:
 #   image: nginx:1.27
 #   volumes:
 #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
 #   ports:
 #     - "80:80"
 #   depends_on:
 #     - api
 #     - frontend
 # Optional: Redis for caching/rate limiting
 # redis:
 #   image: redis:7
 #   ports:
 #     - "6379:6379"