name: CI
on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint & Format
        run: |
          ruff check .
          black --check .
      - name: Tests
        run: pytest -q

docker-build:
  runs-on: ubuntu-latest
  needs: build-test
  steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build API image
      run: docker build -f Dockerfile.api -t house-price-api:ci .
    - name: Build Frontend image
      run: docker build -f Dockerfile.frontend -t house-price-frontend:ci .
 # Optionally push images to a registry if secrets are defined
 # - name: Login to Docker Hub
 #   uses: docker/login-action@v3
 #   with:
 #     username: ${{ secrets.DOCKERHUB_USERNAME }}
 #     password: ${{ secrets.DOCKERHUB_TOKEN }}
 # - name: Push
 #   run: |
 #     docker tag house-price-api:ci ${{ secrets.DOCKERHUB_USERNAME }}/house-price-api:latest
 #     docker tag house-price-frontend:ci ${{ secrets.DOCKERHUB_USERNAME }}/house-price-frontend:latest
 #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/house-price-api:latest
 #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/house-price frontend:latest